Watersite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^water/', include('water.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

water/urls.py
from django.conf.urls import url
from . import views

app_name = 'water'


urlpatterns = [
    url(r'^$', views.index, name='index'),#for index (home)page
    url(r'^(?P<brand_id>[0-9]+)/$', views.detail, name='detail'),#detail of each id
    url(r'^login/$', views.login_view, name='login'),#for login
    url(r'^signup/$',views.Register_View, name='signup'),#for signup
    url(r'^profile/$', views.user_profile, name='profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^profile/change_password/$', views.change_password, name='change_password'),
    url(r'^account', views.account, name='account'),
    url(r'^waterworld/$', views.logoutView, name='logout'),
    url(r'^Pincode/$', views.Pincode, name='Pincode'),
    #url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

]

water/models.py
from django.db import models
from django.contrib.auth.models import  User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Brand(models.Model):
    brand = models.CharField(max_length=100)
    brand_logo = models.FileField()

    def __str__(self):
        return self.brand


class Quality(models.Model):
    brand_info = models.ForeignKey(Brand, on_delete=models.CASCADE , null=True)
    size = models.IntegerField(default=1)
    price = models.IntegerField(default=10)

    def __str__(self):
        return  (str(self.brand_info) +' - '+str(self.size))

class ZipCode(models.Model):
    pin_code = models.CharField(max_length=6, default=111111)

    def __str__(self):
        return self.pin_code
        
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Name = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=300, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    pin_code = models.CharField(max_length=6, null=True)
    mobile_no = models.CharField(max_length=11, null=True)

    def __str__(self):
        return self.user.username


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

water/views.py
from django.contrib.auth import (
    login, logout,get_user_model,
    )
from django.http import HttpResponseRedirect #for return particular page
from django.shortcuts import render, redirect #for go to html page
from .models import Brand, ZipCode, Quality
from django.db.models import Q  #for query search
from .form import LoginForm,  MyRegistrationForm , UserProfileForm, EditProfile#for login or RegisterForm
from django.contrib.auth.decorators import login_required #for log in require
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

User=get_user_model()

#for home page
def index(request):
    all_brand = Brand.objects.all() #all object
    query = request.GET.get("q")#query for search
    if query: #filter query search
        all_brand = all_brand.filter(
            Q(brand__icontains=query))#| Q(size__contains=query) |Q(price__contains=query)
    #return page of index and all_brand  is dict for all above object
    return render(request, 'water/index.html', {'all_brand': all_brand,})



#for detail of each brand

def detail(request, brand_id):
    brandDe = Brand.objects.get(pk=brand_id)#get thought id in brandDe
    #return details page
    
    pin = ZipCode.objects.all()

    #price = Quality.objects.all()
    #pname = request.POST['dropdown1']
    #print(pname)
    '''if request.POST: 
        quality = Quality.objects.get(pname=pname)
        print(quality)'''

    args = {'details': brandDe , 'pin':pin}

    return render(request, 'water/detail.html', args)


#for login
def login_view(request):
    form = LoginForm(request.POST or None)
    if request.POST and form.is_valid():
        user = form.login(request)
        if user:
            login(request, user)
            return redirect('/water')# Redirect to a success page.
            # return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))
    return render(request, 'water/form.html', {'form': form })



#for registration
def Register_View(request):
    if request.method == 'POST':
        form = MyRegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            User.objects.create_user(username=username, email=email, password=password)
            return redirect('/water/login')
    else:
        form = MyRegistrationForm()

    return render(request, 'water/registration_form.html', {'form':form})


@login_required(login_url='/water/login/') #check if user login or not if not then go to login page
# @transaction.atomic
def user_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect('/water')
    else:
        user = request.user
        form = UserProfileForm(instance=request.user.profile)

    return render(request, 'water/profile.html', {'form':form})


#logout
def Pincode(request):
    pin = ZipCode.objects.all()
    return render(request, 'water/pin.html', {'pin':pin})





def account(request):
    # user = UserProfileForm.objects.all()
    # args = {'user':user}
    if request.method =='POST':
        form = UserProfileForm(request.POST)
        print(form.cleaned_data['address'])
        # print(user.profile.address)
    return render(request, 'water/user_profile_details.html')

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfile(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('/water/account/')
    else:
        form = EditProfile(instance=request.user)
    return render(request, 'water/edit_profile.html', {"form":form})


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/water/account/')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'water/change_password.html', {"form":form})


def logoutView(request):
    logout(request)
    return redirect("/water/")

water/templates/water/change_password.html
{% extends 'water/profile_navbar.html' %}
{% block body %}
<div class="profile">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>

{% endblock %}

water/templates/water/form.html
{% block body %}

    <title>login</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'water/style.css' %}">
    <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css'>

    <style type="text/css">
        body{
            background: url('{% static "img/tropical-beach-background-22.jpg" %}') no-repeat center center fixed;

            background-size: cover;

        }
    </style>
<body>

    {% if form.non_field_errors %}
    <ul class='form-errors'>
        {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="wrapper">
    <h1><a style="color: white; margin-left: 550px;" href="{% url 'water:index' %}">WaterWorld</a></h1>
    <form class="form-signin" method="post">
      <h2 class="form-signin-heading" >LogIn</h2>
        {% csrf_token %}
        {{ form.as_p }}
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p style="margin-top: 15px; margin-left: 130px; color: blue;">For Join Us
            <a href="{% url 'water:signup' %}" style="color: red">Join us</a>
        </p>
    </form>
  </div>
</body>
{% endblock %}

water/templates/water/profile_navbar.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.username }}</title>
    {% load staticfiles %}
       <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <style>
        .navbar-default{
            margin-top: 40px;
            margin-left: 100px;
            margin-right: 100px
        }
        .profile{
            margin-top: 20px;
            margin-left: 140px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-default" >

    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'water:index' %}">Water World</a>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-left">
            <li class="">
                <a href="{% url 'water:account' %}">
                 <span class="glyphicon " aria-hidden="true"></span>&nbsp Profile
                </a>
            </li>
            <li class="">
                <a href="{% url 'water:edit_profile' %}">
                 <span class="glyphicon " aria-hidden="true"></span>&nbsp;Edit profile
                </a>
            </li>
            <li class="">
                <a href="{% url 'water:change_password' %}">
                 <span class="glyphicon " aria-hidden="true"></span>&nbsp;Change Password
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <a href="#">
                 <span class="glyphicon " aria-hidden="true"></span>&nbsp;Contact
                </a>
            </li>
            <li>
                <a  class="glyphicon glyphicon-off" href="{% url 'water:logout' %}" onclick="return confirm('Are you sure?')">Logout</a>
            </li>
        </ul>
    </div>
  </div>
    </nav>
</body>
{% block body %}
{% endblock %}
</html>

water/templates/water/registration_form.html
{% block body %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'water/style.css' %}">
	  <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css'>

    <title>SignUp</title>
    <style>
        body{
             background: url('{% static "img/tropical-beach-background-22.jpg" %}') no-repeat center center fixed;

            background-size: cover;
        }
        </style>

<body>
<div class="wrapper">
    <h1><a style="color: white; margin-left: 550px;" href="{% url 'water:index' %}">WaterWorld</a></h1>
    <form class="form-signin" method="post">

      <h2 class="form-signin-heading">SignUp</h2>
        {% csrf_token %}
        {{ form.as_p }}
      <button class="btn btn-lg btn-primary btn-block" type="submit">Registration</button>
    </form>
  </div>

	</body>
{% endblock %}